# Generated by Django 4.0.4 on 2022-05-25 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_api', '0002_productreviews'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductReviews',
            new_name='ProductReview',
        ),
    ]
